// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq96wWEOl06hq2s6fFZJfznr5tgcUqtWI',
    appId: '1:864279864479:web:00e8fe60cbe9d44336eeaa',
    messagingSenderId: '864279864479',
    projectId: 'community-e60ce',
    authDomain: 'community-e60ce.firebaseapp.com',
    storageBucket: 'community-e60ce.firebasestorage.app',
    measurementId: 'G-VNHTHJTQDY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2DZzvXgk1ywWYCFaRQc8ueS43Wd8T7I0',
    appId: '1:864279864479:android:dbfb961ae74c61f336eeaa',
    messagingSenderId: '864279864479',
    projectId: 'community-e60ce',
    storageBucket: 'community-e60ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAudcruEcpjXYRuAGyFC1sTOwuumYHvg1w',
    appId: '1:864279864479:ios:43191d0689d6786936eeaa',
    messagingSenderId: '864279864479',
    projectId: 'community-e60ce',
    storageBucket: 'community-e60ce.firebasestorage.app',
    iosBundleId: 'com.example.community',
  );
}
